### ISSUE TITLE
Prevent concurrent relocations on same pair of servers

### ISSUE THREAD

**Issue by sjmudd** [openark/orchestrator#407]
I don't have a very precise description of the problem but basically it was as follows. A colleague and I were talking about adjusting the topology of some servers in a replication chain and both used the UI at the same time to relocate servers with the end result being that we generated 2 co-masters replicating from each other, each co-master having slaves under it.  These co-masters had originally been intermediate masters below the primary master.

That should not happen. It looks like I decided to relocate one IM under another one and my colleague at the same time did the opposite action.

Configuration of servers were using MySQL 5.7 with Pseudo-GTID.

I discussed with Shlomi and he states that there is a maintenance lock to try to prevent this but it doesn't lock both the server being moved and the destination server.

His suggestion was to add an additional check to see if a lock already exists and not proceed if it's found to avoid this simultaneous relocation happening.

**Comment by sjmudd** [comment]
Oh as a comment on how we fixed this setup of a primary master and some slaves, and 2 independent co-masters replicating from each other and each having their own slaves too.

```
$ orchestrator -c relocate -i <server to move> -d <primary_master>
```

fixed the problem. Nice and +1.

**Comment by shlomi-noach** [comment]
When relocation A below B, A is placed under maintenance, but B isn't, and the intention was to be able to relocate further servers, like C below B. B isn't being changed, so why lock it.

However, this introduces the possibility to concurrently relocate A below B as well as B below A.

I still don't want to add a lock on the would-be parent (B in our story). However, it should be simple enough to avoid relocating A under B in the event B is itself locked, without placing a lock on B.

**Comment by shlomi-noach** [comment]
To add: `IsUnderMaintenance(instanceKey * InstanceKey)` ; to check in `matchBelow()`.

**Comment by shlomi-noach** [comment]
Fixed by #420
